use_frameworks!

target 'LoginController_Example' do
  pod 'LoginController', :path => '../'

  target 'LoginController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
